/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkRouteImport } from './routes/_layout/work'
import { Route as LayoutTreasuryRouteImport } from './routes/_layout/treasury'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutRegisterRouteImport } from './routes/_layout/register'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutApplyRouteImport } from './routes/_layout/apply'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutDocsIndexRouteImport } from './routes/_layout/docs/index'
import { Route as LayoutDocsSlugRouteImport } from './routes/_layout/docs/$slug'
import { Route as LayoutAuthenticatedProfileRouteImport } from './routes/_layout/_authenticated/profile'
import { Route as LayoutAuthenticatedClientForbiddenRouteImport } from './routes/_layout/_authenticated/client-forbidden'
import { Route as LayoutAuthenticatedPlatformRouteRouteImport } from './routes/_layout/_authenticated/platform/route'
import { Route as LayoutAuthenticatedDashboardRouteRouteImport } from './routes/_layout/_authenticated/dashboard/route'
import { Route as LayoutAuthenticatedClientRouteRouteImport } from './routes/_layout/_authenticated/client/route'
import { Route as LayoutAuthenticatedAdminRouteRouteImport } from './routes/_layout/_authenticated/admin/route'
import { Route as LayoutAuthenticatedPlatformIndexRouteImport } from './routes/_layout/_authenticated/platform/index'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedClientIndexRouteImport } from './routes/_layout/_authenticated/client/index'
import { Route as LayoutAuthenticatedAdminIndexRouteImport } from './routes/_layout/_authenticated/admin/index'
import { Route as LayoutAuthenticatedClientPlanRouteImport } from './routes/_layout/_authenticated/client/plan'
import { Route as LayoutAuthenticatedAdminSettingsRouteImport } from './routes/_layout/_authenticated/admin/settings'
import { Route as LayoutAuthenticatedAdminMembersRouteImport } from './routes/_layout/_authenticated/admin/members'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'
import { Route as LayoutAuthenticatedClientReportsIndexRouteImport } from './routes/_layout/_authenticated/client/reports/index'
import { Route as LayoutAuthenticatedClientProjectsIndexRouteImport } from './routes/_layout/_authenticated/client/projects/index'
import { Route as LayoutAuthenticatedAdminReportsIndexRouteImport } from './routes/_layout/_authenticated/admin/reports/index'
import { Route as LayoutAuthenticatedAdminProjectsIndexRouteImport } from './routes/_layout/_authenticated/admin/projects/index'
import { Route as LayoutAuthenticatedAdminEngagementsIndexRouteImport } from './routes/_layout/_authenticated/admin/engagements/index'
import { Route as LayoutAuthenticatedAdminContributorsIndexRouteImport } from './routes/_layout/_authenticated/admin/contributors/index'
import { Route as LayoutAuthenticatedAdminBudgetsIndexRouteImport } from './routes/_layout/_authenticated/admin/budgets/index'
import { Route as LayoutAuthenticatedAdminBillingsIndexRouteImport } from './routes/_layout/_authenticated/admin/billings/index'
import { Route as LayoutAuthenticatedAdminApplicationsIndexRouteImport } from './routes/_layout/_authenticated/admin/applications/index'
import { Route as LayoutAuthenticatedClientProjectsSlugRouteImport } from './routes/_layout/_authenticated/client/projects/$slug'
import { Route as LayoutAuthenticatedAdminProjectsSlugRouteImport } from './routes/_layout/_authenticated/admin/projects/$slug'
import { Route as LayoutAuthenticatedAdminContributorsNearAccountRouteImport } from './routes/_layout/_authenticated/admin/contributors/$nearAccount'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkRoute = LayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTreasuryRoute = LayoutTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegisterRoute = LayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplyRoute = LayoutApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsSlugRoute = LayoutDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedProfileRoute =
  LayoutAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedClientForbiddenRoute =
  LayoutAuthenticatedClientForbiddenRouteImport.update({
    id: '/client-forbidden',
    path: '/client-forbidden',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPlatformRouteRoute =
  LayoutAuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRouteRoute =
  LayoutAuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedClientRouteRoute =
  LayoutAuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminRouteRoute =
  LayoutAuthenticatedAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPlatformIndexRoute =
  LayoutAuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedPlatformRouteRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRouteRoute,
  } as any)
const LayoutAuthenticatedClientIndexRoute =
  LayoutAuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedAdminIndexRoute =
  LayoutAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedClientPlanRoute =
  LayoutAuthenticatedClientPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedAdminSettingsRoute =
  LayoutAuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminMembersRoute =
  LayoutAuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedClientReportsIndexRoute =
  LayoutAuthenticatedClientReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedClientProjectsIndexRoute =
  LayoutAuthenticatedClientProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedAdminReportsIndexRoute =
  LayoutAuthenticatedAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminProjectsIndexRoute =
  LayoutAuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminEngagementsIndexRoute =
  LayoutAuthenticatedAdminEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminContributorsIndexRoute =
  LayoutAuthenticatedAdminContributorsIndexRouteImport.update({
    id: '/contributors/',
    path: '/contributors/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminBudgetsIndexRoute =
  LayoutAuthenticatedAdminBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminBillingsIndexRoute =
  LayoutAuthenticatedAdminBillingsIndexRouteImport.update({
    id: '/billings/',
    path: '/billings/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminApplicationsIndexRoute =
  LayoutAuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedClientProjectsSlugRoute =
  LayoutAuthenticatedClientProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedAdminProjectsSlugRoute =
  LayoutAuthenticatedAdminProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminContributorsNearAccountRoute =
  LayoutAuthenticatedAdminContributorsNearAccountRouteImport.update({
    id: '/contributors/$nearAccount',
    path: '/contributors/$nearAccount',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/login': typeof LayoutLoginRoute
  '/register': typeof LayoutRegisterRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/admin': typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  '/client': typeof LayoutAuthenticatedClientRouteRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteRouteWithChildren
  '/platform': typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  '/client-forbidden': typeof LayoutAuthenticatedClientForbiddenRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/client/plan': typeof LayoutAuthenticatedClientPlanRoute
  '/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/client/': typeof LayoutAuthenticatedClientIndexRoute
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/platform/': typeof LayoutAuthenticatedPlatformIndexRoute
  '/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/client/projects/$slug': typeof LayoutAuthenticatedClientProjectsSlugRoute
  '/admin/applications/': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/admin/billings/': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/admin/budgets/': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/admin/contributors/': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/admin/engagements/': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/admin/projects/': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/admin/reports/': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/client/projects/': typeof LayoutAuthenticatedClientProjectsIndexRoute
  '/client/reports/': typeof LayoutAuthenticatedClientReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/login': typeof LayoutLoginRoute
  '/register': typeof LayoutRegisterRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/client-forbidden': typeof LayoutAuthenticatedClientForbiddenRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/client/plan': typeof LayoutAuthenticatedClientPlanRoute
  '/admin': typeof LayoutAuthenticatedAdminIndexRoute
  '/client': typeof LayoutAuthenticatedClientIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/platform': typeof LayoutAuthenticatedPlatformIndexRoute
  '/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/client/projects/$slug': typeof LayoutAuthenticatedClientProjectsSlugRoute
  '/admin/applications': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/admin/billings': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/admin/budgets': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/admin/contributors': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/admin/engagements': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/admin/projects': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/admin/reports': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/client/projects': typeof LayoutAuthenticatedClientProjectsIndexRoute
  '/client/reports': typeof LayoutAuthenticatedClientReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/apply': typeof LayoutApplyRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/register': typeof LayoutRegisterRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/treasury': typeof LayoutTreasuryRoute
  '/_layout/work': typeof LayoutWorkRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  '/_layout/_authenticated/client': typeof LayoutAuthenticatedClientRouteRouteWithChildren
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteRouteWithChildren
  '/_layout/_authenticated/platform': typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  '/_layout/_authenticated/client-forbidden': typeof LayoutAuthenticatedClientForbiddenRoute
  '/_layout/_authenticated/profile': typeof LayoutAuthenticatedProfileRoute
  '/_layout/docs/$slug': typeof LayoutDocsSlugRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/_layout/_authenticated/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/_layout/_authenticated/client/plan': typeof LayoutAuthenticatedClientPlanRoute
  '/_layout/_authenticated/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/_layout/_authenticated/client/': typeof LayoutAuthenticatedClientIndexRoute
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/platform/': typeof LayoutAuthenticatedPlatformIndexRoute
  '/_layout/_authenticated/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/_layout/_authenticated/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/_layout/_authenticated/client/projects/$slug': typeof LayoutAuthenticatedClientProjectsSlugRoute
  '/_layout/_authenticated/admin/applications/': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/_layout/_authenticated/admin/billings/': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/_layout/_authenticated/admin/budgets/': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/_layout/_authenticated/admin/contributors/': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/_layout/_authenticated/admin/engagements/': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/_layout/_authenticated/admin/projects/': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/_layout/_authenticated/admin/reports/': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/_layout/_authenticated/client/projects/': typeof LayoutAuthenticatedClientProjectsIndexRoute
  '/_layout/_authenticated/client/reports/': typeof LayoutAuthenticatedClientReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/login'
    | '/register'
    | '/team'
    | '/treasury'
    | '/work'
    | '/admin'
    | '/client'
    | '/dashboard'
    | '/platform'
    | '/client-forbidden'
    | '/profile'
    | '/docs/$slug'
    | '/docs/'
    | '/accept-invitation/$id'
    | '/admin/members'
    | '/admin/settings'
    | '/client/plan'
    | '/admin/'
    | '/client/'
    | '/dashboard/'
    | '/platform/'
    | '/admin/contributors/$nearAccount'
    | '/admin/projects/$slug'
    | '/client/projects/$slug'
    | '/admin/applications/'
    | '/admin/billings/'
    | '/admin/budgets/'
    | '/admin/contributors/'
    | '/admin/engagements/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/client/projects/'
    | '/client/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/login'
    | '/register'
    | '/team'
    | '/treasury'
    | '/work'
    | '/client-forbidden'
    | '/profile'
    | '/docs/$slug'
    | '/docs'
    | '/accept-invitation/$id'
    | '/admin/members'
    | '/admin/settings'
    | '/client/plan'
    | '/admin'
    | '/client'
    | '/dashboard'
    | '/platform'
    | '/admin/contributors/$nearAccount'
    | '/admin/projects/$slug'
    | '/client/projects/$slug'
    | '/admin/applications'
    | '/admin/billings'
    | '/admin/budgets'
    | '/admin/contributors'
    | '/admin/engagements'
    | '/admin/projects'
    | '/admin/reports'
    | '/client/projects'
    | '/client/reports'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/apply'
    | '/_layout/contact'
    | '/_layout/login'
    | '/_layout/register'
    | '/_layout/team'
    | '/_layout/treasury'
    | '/_layout/work'
    | '/_layout/'
    | '/_layout/_authenticated/admin'
    | '/_layout/_authenticated/client'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/platform'
    | '/_layout/_authenticated/client-forbidden'
    | '/_layout/_authenticated/profile'
    | '/_layout/docs/$slug'
    | '/_layout/docs/'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/admin/members'
    | '/_layout/_authenticated/admin/settings'
    | '/_layout/_authenticated/client/plan'
    | '/_layout/_authenticated/admin/'
    | '/_layout/_authenticated/client/'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/platform/'
    | '/_layout/_authenticated/admin/contributors/$nearAccount'
    | '/_layout/_authenticated/admin/projects/$slug'
    | '/_layout/_authenticated/client/projects/$slug'
    | '/_layout/_authenticated/admin/applications/'
    | '/_layout/_authenticated/admin/billings/'
    | '/_layout/_authenticated/admin/budgets/'
    | '/_layout/_authenticated/admin/contributors/'
    | '/_layout/_authenticated/admin/engagements/'
    | '/_layout/_authenticated/admin/projects/'
    | '/_layout/_authenticated/admin/reports/'
    | '/_layout/_authenticated/client/projects/'
    | '/_layout/_authenticated/client/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work': {
      id: '/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof LayoutWorkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/treasury': {
      id: '/_layout/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof LayoutTreasuryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apply': {
      id: '/_layout/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof LayoutApplyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/$slug': {
      id: '/_layout/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof LayoutDocsSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/profile': {
      id: '/_layout/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthenticatedProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/client-forbidden': {
      id: '/_layout/_authenticated/client-forbidden'
      path: '/client-forbidden'
      fullPath: '/client-forbidden'
      preLoaderRoute: typeof LayoutAuthenticatedClientForbiddenRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/platform': {
      id: '/_layout/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof LayoutAuthenticatedPlatformRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/client': {
      id: '/_layout/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof LayoutAuthenticatedClientRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/platform/': {
      id: '/_layout/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof LayoutAuthenticatedPlatformIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedPlatformRouteRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRouteRoute
    }
    '/_layout/_authenticated/client/': {
      id: '/_layout/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof LayoutAuthenticatedClientIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/admin/': {
      id: '/_layout/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/client/plan': {
      id: '/_layout/_authenticated/client/plan'
      path: '/plan'
      fullPath: '/client/plan'
      preLoaderRoute: typeof LayoutAuthenticatedClientPlanRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/admin/settings': {
      id: '/_layout/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAuthenticatedAdminSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/members': {
      id: '/_layout/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof LayoutAuthenticatedAdminMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/client/reports/': {
      id: '/_layout/_authenticated/client/reports/'
      path: '/reports'
      fullPath: '/client/reports/'
      preLoaderRoute: typeof LayoutAuthenticatedClientReportsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/client/projects/': {
      id: '/_layout/_authenticated/client/projects/'
      path: '/projects'
      fullPath: '/client/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedClientProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/admin/reports/': {
      id: '/_layout/_authenticated/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/projects/': {
      id: '/_layout/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/engagements/': {
      id: '/_layout/_authenticated/admin/engagements/'
      path: '/engagements'
      fullPath: '/admin/engagements/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminEngagementsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/contributors/': {
      id: '/_layout/_authenticated/admin/contributors/'
      path: '/contributors'
      fullPath: '/admin/contributors/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminContributorsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/budgets/': {
      id: '/_layout/_authenticated/admin/budgets/'
      path: '/budgets'
      fullPath: '/admin/budgets/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminBudgetsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/billings/': {
      id: '/_layout/_authenticated/admin/billings/'
      path: '/billings'
      fullPath: '/admin/billings/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminBillingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/applications/': {
      id: '/_layout/_authenticated/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/client/projects/$slug': {
      id: '/_layout/_authenticated/client/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/client/projects/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedClientProjectsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/admin/projects/$slug': {
      id: '/_layout/_authenticated/admin/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/admin/projects/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedAdminProjectsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/contributors/$nearAccount': {
      id: '/_layout/_authenticated/admin/contributors/$nearAccount'
      path: '/contributors/$nearAccount'
      fullPath: '/admin/contributors/$nearAccount'
      preLoaderRoute: typeof LayoutAuthenticatedAdminContributorsNearAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteRouteChildren {
  LayoutAuthenticatedAdminMembersRoute: typeof LayoutAuthenticatedAdminMembersRoute
  LayoutAuthenticatedAdminSettingsRoute: typeof LayoutAuthenticatedAdminSettingsRoute
  LayoutAuthenticatedAdminIndexRoute: typeof LayoutAuthenticatedAdminIndexRoute
  LayoutAuthenticatedAdminContributorsNearAccountRoute: typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  LayoutAuthenticatedAdminProjectsSlugRoute: typeof LayoutAuthenticatedAdminProjectsSlugRoute
  LayoutAuthenticatedAdminApplicationsIndexRoute: typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  LayoutAuthenticatedAdminBillingsIndexRoute: typeof LayoutAuthenticatedAdminBillingsIndexRoute
  LayoutAuthenticatedAdminBudgetsIndexRoute: typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  LayoutAuthenticatedAdminContributorsIndexRoute: typeof LayoutAuthenticatedAdminContributorsIndexRoute
  LayoutAuthenticatedAdminEngagementsIndexRoute: typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  LayoutAuthenticatedAdminProjectsIndexRoute: typeof LayoutAuthenticatedAdminProjectsIndexRoute
  LayoutAuthenticatedAdminReportsIndexRoute: typeof LayoutAuthenticatedAdminReportsIndexRoute
}

const LayoutAuthenticatedAdminRouteRouteChildren: LayoutAuthenticatedAdminRouteRouteChildren =
  {
    LayoutAuthenticatedAdminMembersRoute: LayoutAuthenticatedAdminMembersRoute,
    LayoutAuthenticatedAdminSettingsRoute:
      LayoutAuthenticatedAdminSettingsRoute,
    LayoutAuthenticatedAdminIndexRoute: LayoutAuthenticatedAdminIndexRoute,
    LayoutAuthenticatedAdminContributorsNearAccountRoute:
      LayoutAuthenticatedAdminContributorsNearAccountRoute,
    LayoutAuthenticatedAdminProjectsSlugRoute:
      LayoutAuthenticatedAdminProjectsSlugRoute,
    LayoutAuthenticatedAdminApplicationsIndexRoute:
      LayoutAuthenticatedAdminApplicationsIndexRoute,
    LayoutAuthenticatedAdminBillingsIndexRoute:
      LayoutAuthenticatedAdminBillingsIndexRoute,
    LayoutAuthenticatedAdminBudgetsIndexRoute:
      LayoutAuthenticatedAdminBudgetsIndexRoute,
    LayoutAuthenticatedAdminContributorsIndexRoute:
      LayoutAuthenticatedAdminContributorsIndexRoute,
    LayoutAuthenticatedAdminEngagementsIndexRoute:
      LayoutAuthenticatedAdminEngagementsIndexRoute,
    LayoutAuthenticatedAdminProjectsIndexRoute:
      LayoutAuthenticatedAdminProjectsIndexRoute,
    LayoutAuthenticatedAdminReportsIndexRoute:
      LayoutAuthenticatedAdminReportsIndexRoute,
  }

const LayoutAuthenticatedAdminRouteRouteWithChildren =
  LayoutAuthenticatedAdminRouteRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteRouteChildren,
  )

interface LayoutAuthenticatedClientRouteRouteChildren {
  LayoutAuthenticatedClientPlanRoute: typeof LayoutAuthenticatedClientPlanRoute
  LayoutAuthenticatedClientIndexRoute: typeof LayoutAuthenticatedClientIndexRoute
  LayoutAuthenticatedClientProjectsSlugRoute: typeof LayoutAuthenticatedClientProjectsSlugRoute
  LayoutAuthenticatedClientProjectsIndexRoute: typeof LayoutAuthenticatedClientProjectsIndexRoute
  LayoutAuthenticatedClientReportsIndexRoute: typeof LayoutAuthenticatedClientReportsIndexRoute
}

const LayoutAuthenticatedClientRouteRouteChildren: LayoutAuthenticatedClientRouteRouteChildren =
  {
    LayoutAuthenticatedClientPlanRoute: LayoutAuthenticatedClientPlanRoute,
    LayoutAuthenticatedClientIndexRoute: LayoutAuthenticatedClientIndexRoute,
    LayoutAuthenticatedClientProjectsSlugRoute:
      LayoutAuthenticatedClientProjectsSlugRoute,
    LayoutAuthenticatedClientProjectsIndexRoute:
      LayoutAuthenticatedClientProjectsIndexRoute,
    LayoutAuthenticatedClientReportsIndexRoute:
      LayoutAuthenticatedClientReportsIndexRoute,
  }

const LayoutAuthenticatedClientRouteRouteWithChildren =
  LayoutAuthenticatedClientRouteRoute._addFileChildren(
    LayoutAuthenticatedClientRouteRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteRouteChildren {
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
}

const LayoutAuthenticatedDashboardRouteRouteChildren: LayoutAuthenticatedDashboardRouteRouteChildren =
  {
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
  }

const LayoutAuthenticatedDashboardRouteRouteWithChildren =
  LayoutAuthenticatedDashboardRouteRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteRouteChildren,
  )

interface LayoutAuthenticatedPlatformRouteRouteChildren {
  LayoutAuthenticatedPlatformIndexRoute: typeof LayoutAuthenticatedPlatformIndexRoute
}

const LayoutAuthenticatedPlatformRouteRouteChildren: LayoutAuthenticatedPlatformRouteRouteChildren =
  {
    LayoutAuthenticatedPlatformIndexRoute:
      LayoutAuthenticatedPlatformIndexRoute,
  }

const LayoutAuthenticatedPlatformRouteRouteWithChildren =
  LayoutAuthenticatedPlatformRouteRoute._addFileChildren(
    LayoutAuthenticatedPlatformRouteRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRouteRoute: typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  LayoutAuthenticatedClientRouteRoute: typeof LayoutAuthenticatedClientRouteRouteWithChildren
  LayoutAuthenticatedDashboardRouteRoute: typeof LayoutAuthenticatedDashboardRouteRouteWithChildren
  LayoutAuthenticatedPlatformRouteRoute: typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  LayoutAuthenticatedClientForbiddenRoute: typeof LayoutAuthenticatedClientForbiddenRoute
  LayoutAuthenticatedProfileRoute: typeof LayoutAuthenticatedProfileRoute
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRouteRoute:
    LayoutAuthenticatedAdminRouteRouteWithChildren,
  LayoutAuthenticatedClientRouteRoute:
    LayoutAuthenticatedClientRouteRouteWithChildren,
  LayoutAuthenticatedDashboardRouteRoute:
    LayoutAuthenticatedDashboardRouteRouteWithChildren,
  LayoutAuthenticatedPlatformRouteRoute:
    LayoutAuthenticatedPlatformRouteRouteWithChildren,
  LayoutAuthenticatedClientForbiddenRoute:
    LayoutAuthenticatedClientForbiddenRoute,
  LayoutAuthenticatedProfileRoute: LayoutAuthenticatedProfileRoute,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutApplyRoute: typeof LayoutApplyRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutRegisterRoute: typeof LayoutRegisterRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutTreasuryRoute: typeof LayoutTreasuryRoute
  LayoutWorkRoute: typeof LayoutWorkRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDocsSlugRoute: typeof LayoutDocsSlugRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutApplyRoute: LayoutApplyRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutRegisterRoute: LayoutRegisterRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutTreasuryRoute: LayoutTreasuryRoute,
  LayoutWorkRoute: LayoutWorkRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDocsSlugRoute: LayoutDocsSlugRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
