/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkRouteImport } from './routes/_layout/work'
import { Route as LayoutTreasuryRouteImport } from './routes/_layout/treasury'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutSignInRouteImport } from './routes/_layout/sign-in'
import { Route as LayoutResetPasswordRouteImport } from './routes/_layout/reset-password'
import { Route as LayoutRegisterRouteImport } from './routes/_layout/register'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutApplyRouteImport } from './routes/_layout/apply'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutDocsIndexRouteImport } from './routes/_layout/docs/index'
import { Route as LayoutDocsSlugRouteImport } from './routes/_layout/docs/$slug'
import { Route as LayoutAcceptInvitationIdRouteImport } from './routes/_layout/accept-invitation/$id'
import { Route as LayoutAuthenticatedWelcomeRouteImport } from './routes/_layout/_authenticated/welcome'
import { Route as LayoutAuthenticatedProfileRouteImport } from './routes/_layout/_authenticated/profile'
import { Route as LayoutAuthenticatedNotificationsRouteImport } from './routes/_layout/_authenticated/notifications'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedPlatformRouteRouteImport } from './routes/_layout/_authenticated/platform/route'
import { Route as LayoutAuthenticatedClientRouteRouteImport } from './routes/_layout/_authenticated/client/route'
import { Route as LayoutAuthenticatedAdminRouteRouteImport } from './routes/_layout/_authenticated/admin/route'
import { Route as LayoutAuthenticatedPlatformIndexRouteImport } from './routes/_layout/_authenticated/platform/index'
import { Route as LayoutAuthenticatedClientIndexRouteImport } from './routes/_layout/_authenticated/client/index'
import { Route as LayoutAuthenticatedAdminIndexRouteImport } from './routes/_layout/_authenticated/admin/index'
import { Route as LayoutAuthenticatedAdminSettingsRouteImport } from './routes/_layout/_authenticated/admin/settings'
import { Route as LayoutAuthenticatedAdminMembersRouteImport } from './routes/_layout/_authenticated/admin/members'
import { Route as LayoutAuthenticatedClientEngagementIdRouteRouteImport } from './routes/_layout/_authenticated/client/$engagementId/route'
import { Route as LayoutAuthenticatedClientEngagementIdIndexRouteImport } from './routes/_layout/_authenticated/client/$engagementId/index'
import { Route as LayoutAuthenticatedAdminReportsIndexRouteImport } from './routes/_layout/_authenticated/admin/reports/index'
import { Route as LayoutAuthenticatedAdminProjectsIndexRouteImport } from './routes/_layout/_authenticated/admin/projects/index'
import { Route as LayoutAuthenticatedAdminEngagementsIndexRouteImport } from './routes/_layout/_authenticated/admin/engagements/index'
import { Route as LayoutAuthenticatedAdminContributorsIndexRouteImport } from './routes/_layout/_authenticated/admin/contributors/index'
import { Route as LayoutAuthenticatedAdminBudgetsIndexRouteImport } from './routes/_layout/_authenticated/admin/budgets/index'
import { Route as LayoutAuthenticatedAdminBillingsIndexRouteImport } from './routes/_layout/_authenticated/admin/billings/index'
import { Route as LayoutAuthenticatedAdminApplicationsIndexRouteImport } from './routes/_layout/_authenticated/admin/applications/index'
import { Route as LayoutAuthenticatedClientEngagementIdReportsRouteImport } from './routes/_layout/_authenticated/client/$engagementId/reports'
import { Route as LayoutAuthenticatedClientEngagementIdPrepaymentsRouteImport } from './routes/_layout/_authenticated/client/$engagementId/prepayments'
import { Route as LayoutAuthenticatedClientEngagementIdBillingsRouteImport } from './routes/_layout/_authenticated/client/$engagementId/billings'
import { Route as LayoutAuthenticatedAdminProjectsSlugRouteImport } from './routes/_layout/_authenticated/admin/projects/$slug'
import { Route as LayoutAuthenticatedAdminEngagementsEngagementIdRouteImport } from './routes/_layout/_authenticated/admin/engagements/$engagementId'
import { Route as LayoutAuthenticatedAdminContributorsNearAccountRouteImport } from './routes/_layout/_authenticated/admin/contributors/$nearAccount'
import { Route as LayoutAuthenticatedClientEngagementIdProjectsIndexRouteImport } from './routes/_layout/_authenticated/client/$engagementId/projects/index'
import { Route as LayoutAuthenticatedClientEngagementIdProjectsSlugRouteImport } from './routes/_layout/_authenticated/client/$engagementId/projects/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkRoute = LayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTreasuryRoute = LayoutTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignInRoute = LayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResetPasswordRoute = LayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegisterRoute = LayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplyRoute = LayoutApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsSlugRoute = LayoutDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAcceptInvitationIdRoute =
  LayoutAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedWelcomeRoute =
  LayoutAuthenticatedWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProfileRoute =
  LayoutAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedNotificationsRoute =
  LayoutAuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPlatformRouteRoute =
  LayoutAuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedClientRouteRoute =
  LayoutAuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminRouteRoute =
  LayoutAuthenticatedAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedPlatformIndexRoute =
  LayoutAuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedPlatformRouteRoute,
  } as any)
const LayoutAuthenticatedClientIndexRoute =
  LayoutAuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedAdminIndexRoute =
  LayoutAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminSettingsRoute =
  LayoutAuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminMembersRoute =
  LayoutAuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdRouteRoute =
  LayoutAuthenticatedClientEngagementIdRouteRouteImport.update({
    id: '/$engagementId',
    path: '/$engagementId',
    getParentRoute: () => LayoutAuthenticatedClientRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdIndexRoute =
  LayoutAuthenticatedClientEngagementIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)
const LayoutAuthenticatedAdminReportsIndexRoute =
  LayoutAuthenticatedAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminProjectsIndexRoute =
  LayoutAuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminEngagementsIndexRoute =
  LayoutAuthenticatedAdminEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminContributorsIndexRoute =
  LayoutAuthenticatedAdminContributorsIndexRouteImport.update({
    id: '/contributors/',
    path: '/contributors/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminBudgetsIndexRoute =
  LayoutAuthenticatedAdminBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminBillingsIndexRoute =
  LayoutAuthenticatedAdminBillingsIndexRouteImport.update({
    id: '/billings/',
    path: '/billings/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminApplicationsIndexRoute =
  LayoutAuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdReportsRoute =
  LayoutAuthenticatedClientEngagementIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdPrepaymentsRoute =
  LayoutAuthenticatedClientEngagementIdPrepaymentsRouteImport.update({
    id: '/prepayments',
    path: '/prepayments',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdBillingsRoute =
  LayoutAuthenticatedClientEngagementIdBillingsRouteImport.update({
    id: '/billings',
    path: '/billings',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)
const LayoutAuthenticatedAdminProjectsSlugRoute =
  LayoutAuthenticatedAdminProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminEngagementsEngagementIdRoute =
  LayoutAuthenticatedAdminEngagementsEngagementIdRouteImport.update({
    id: '/engagements/$engagementId',
    path: '/engagements/$engagementId',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedAdminContributorsNearAccountRoute =
  LayoutAuthenticatedAdminContributorsNearAccountRouteImport.update({
    id: '/contributors/$nearAccount',
    path: '/contributors/$nearAccount',
    getParentRoute: () => LayoutAuthenticatedAdminRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdProjectsIndexRoute =
  LayoutAuthenticatedClientEngagementIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)
const LayoutAuthenticatedClientEngagementIdProjectsSlugRoute =
  LayoutAuthenticatedClientEngagementIdProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => LayoutAuthenticatedClientEngagementIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/register': typeof LayoutRegisterRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/sign-in': typeof LayoutSignInRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/admin': typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  '/client': typeof LayoutAuthenticatedClientRouteRouteWithChildren
  '/platform': typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/notifications': typeof LayoutAuthenticatedNotificationsRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/welcome': typeof LayoutAuthenticatedWelcomeRoute
  '/accept-invitation/$id': typeof LayoutAcceptInvitationIdRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/client/$engagementId': typeof LayoutAuthenticatedClientEngagementIdRouteRouteWithChildren
  '/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/client/': typeof LayoutAuthenticatedClientIndexRoute
  '/platform/': typeof LayoutAuthenticatedPlatformIndexRoute
  '/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/admin/engagements/$engagementId': typeof LayoutAuthenticatedAdminEngagementsEngagementIdRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/client/$engagementId/billings': typeof LayoutAuthenticatedClientEngagementIdBillingsRoute
  '/client/$engagementId/prepayments': typeof LayoutAuthenticatedClientEngagementIdPrepaymentsRoute
  '/client/$engagementId/reports': typeof LayoutAuthenticatedClientEngagementIdReportsRoute
  '/admin/applications/': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/admin/billings/': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/admin/budgets/': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/admin/contributors/': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/admin/engagements/': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/admin/projects/': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/admin/reports/': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/client/$engagementId/': typeof LayoutAuthenticatedClientEngagementIdIndexRoute
  '/client/$engagementId/projects/$slug': typeof LayoutAuthenticatedClientEngagementIdProjectsSlugRoute
  '/client/$engagementId/projects/': typeof LayoutAuthenticatedClientEngagementIdProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/register': typeof LayoutRegisterRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/sign-in': typeof LayoutSignInRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/notifications': typeof LayoutAuthenticatedNotificationsRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/welcome': typeof LayoutAuthenticatedWelcomeRoute
  '/accept-invitation/$id': typeof LayoutAcceptInvitationIdRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/admin': typeof LayoutAuthenticatedAdminIndexRoute
  '/client': typeof LayoutAuthenticatedClientIndexRoute
  '/platform': typeof LayoutAuthenticatedPlatformIndexRoute
  '/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/admin/engagements/$engagementId': typeof LayoutAuthenticatedAdminEngagementsEngagementIdRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/client/$engagementId/billings': typeof LayoutAuthenticatedClientEngagementIdBillingsRoute
  '/client/$engagementId/prepayments': typeof LayoutAuthenticatedClientEngagementIdPrepaymentsRoute
  '/client/$engagementId/reports': typeof LayoutAuthenticatedClientEngagementIdReportsRoute
  '/admin/applications': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/admin/billings': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/admin/budgets': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/admin/contributors': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/admin/engagements': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/admin/projects': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/admin/reports': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/client/$engagementId': typeof LayoutAuthenticatedClientEngagementIdIndexRoute
  '/client/$engagementId/projects/$slug': typeof LayoutAuthenticatedClientEngagementIdProjectsSlugRoute
  '/client/$engagementId/projects': typeof LayoutAuthenticatedClientEngagementIdProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/apply': typeof LayoutApplyRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/register': typeof LayoutRegisterRoute
  '/_layout/reset-password': typeof LayoutResetPasswordRoute
  '/_layout/sign-in': typeof LayoutSignInRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/treasury': typeof LayoutTreasuryRoute
  '/_layout/work': typeof LayoutWorkRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  '/_layout/_authenticated/client': typeof LayoutAuthenticatedClientRouteRouteWithChildren
  '/_layout/_authenticated/platform': typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/_layout/_authenticated/notifications': typeof LayoutAuthenticatedNotificationsRoute
  '/_layout/_authenticated/profile': typeof LayoutAuthenticatedProfileRoute
  '/_layout/_authenticated/welcome': typeof LayoutAuthenticatedWelcomeRoute
  '/_layout/accept-invitation/$id': typeof LayoutAcceptInvitationIdRoute
  '/_layout/docs/$slug': typeof LayoutDocsSlugRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/_authenticated/client/$engagementId': typeof LayoutAuthenticatedClientEngagementIdRouteRouteWithChildren
  '/_layout/_authenticated/admin/members': typeof LayoutAuthenticatedAdminMembersRoute
  '/_layout/_authenticated/admin/settings': typeof LayoutAuthenticatedAdminSettingsRoute
  '/_layout/_authenticated/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/_layout/_authenticated/client/': typeof LayoutAuthenticatedClientIndexRoute
  '/_layout/_authenticated/platform/': typeof LayoutAuthenticatedPlatformIndexRoute
  '/_layout/_authenticated/admin/contributors/$nearAccount': typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  '/_layout/_authenticated/admin/engagements/$engagementId': typeof LayoutAuthenticatedAdminEngagementsEngagementIdRoute
  '/_layout/_authenticated/admin/projects/$slug': typeof LayoutAuthenticatedAdminProjectsSlugRoute
  '/_layout/_authenticated/client/$engagementId/billings': typeof LayoutAuthenticatedClientEngagementIdBillingsRoute
  '/_layout/_authenticated/client/$engagementId/prepayments': typeof LayoutAuthenticatedClientEngagementIdPrepaymentsRoute
  '/_layout/_authenticated/client/$engagementId/reports': typeof LayoutAuthenticatedClientEngagementIdReportsRoute
  '/_layout/_authenticated/admin/applications/': typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  '/_layout/_authenticated/admin/billings/': typeof LayoutAuthenticatedAdminBillingsIndexRoute
  '/_layout/_authenticated/admin/budgets/': typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  '/_layout/_authenticated/admin/contributors/': typeof LayoutAuthenticatedAdminContributorsIndexRoute
  '/_layout/_authenticated/admin/engagements/': typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  '/_layout/_authenticated/admin/projects/': typeof LayoutAuthenticatedAdminProjectsIndexRoute
  '/_layout/_authenticated/admin/reports/': typeof LayoutAuthenticatedAdminReportsIndexRoute
  '/_layout/_authenticated/client/$engagementId/': typeof LayoutAuthenticatedClientEngagementIdIndexRoute
  '/_layout/_authenticated/client/$engagementId/projects/$slug': typeof LayoutAuthenticatedClientEngagementIdProjectsSlugRoute
  '/_layout/_authenticated/client/$engagementId/projects/': typeof LayoutAuthenticatedClientEngagementIdProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/register'
    | '/reset-password'
    | '/sign-in'
    | '/team'
    | '/treasury'
    | '/work'
    | '/admin'
    | '/client'
    | '/platform'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/welcome'
    | '/accept-invitation/$id'
    | '/docs/$slug'
    | '/docs/'
    | '/client/$engagementId'
    | '/admin/members'
    | '/admin/settings'
    | '/admin/'
    | '/client/'
    | '/platform/'
    | '/admin/contributors/$nearAccount'
    | '/admin/engagements/$engagementId'
    | '/admin/projects/$slug'
    | '/client/$engagementId/billings'
    | '/client/$engagementId/prepayments'
    | '/client/$engagementId/reports'
    | '/admin/applications/'
    | '/admin/billings/'
    | '/admin/budgets/'
    | '/admin/contributors/'
    | '/admin/engagements/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/client/$engagementId/'
    | '/client/$engagementId/projects/$slug'
    | '/client/$engagementId/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/register'
    | '/reset-password'
    | '/sign-in'
    | '/team'
    | '/treasury'
    | '/work'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/welcome'
    | '/accept-invitation/$id'
    | '/docs/$slug'
    | '/docs'
    | '/admin/members'
    | '/admin/settings'
    | '/admin'
    | '/client'
    | '/platform'
    | '/admin/contributors/$nearAccount'
    | '/admin/engagements/$engagementId'
    | '/admin/projects/$slug'
    | '/client/$engagementId/billings'
    | '/client/$engagementId/prepayments'
    | '/client/$engagementId/reports'
    | '/admin/applications'
    | '/admin/billings'
    | '/admin/budgets'
    | '/admin/contributors'
    | '/admin/engagements'
    | '/admin/projects'
    | '/admin/reports'
    | '/client/$engagementId'
    | '/client/$engagementId/projects/$slug'
    | '/client/$engagementId/projects'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/apply'
    | '/_layout/contact'
    | '/_layout/register'
    | '/_layout/reset-password'
    | '/_layout/sign-in'
    | '/_layout/team'
    | '/_layout/treasury'
    | '/_layout/work'
    | '/_layout/'
    | '/_layout/_authenticated/admin'
    | '/_layout/_authenticated/client'
    | '/_layout/_authenticated/platform'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/notifications'
    | '/_layout/_authenticated/profile'
    | '/_layout/_authenticated/welcome'
    | '/_layout/accept-invitation/$id'
    | '/_layout/docs/$slug'
    | '/_layout/docs/'
    | '/_layout/_authenticated/client/$engagementId'
    | '/_layout/_authenticated/admin/members'
    | '/_layout/_authenticated/admin/settings'
    | '/_layout/_authenticated/admin/'
    | '/_layout/_authenticated/client/'
    | '/_layout/_authenticated/platform/'
    | '/_layout/_authenticated/admin/contributors/$nearAccount'
    | '/_layout/_authenticated/admin/engagements/$engagementId'
    | '/_layout/_authenticated/admin/projects/$slug'
    | '/_layout/_authenticated/client/$engagementId/billings'
    | '/_layout/_authenticated/client/$engagementId/prepayments'
    | '/_layout/_authenticated/client/$engagementId/reports'
    | '/_layout/_authenticated/admin/applications/'
    | '/_layout/_authenticated/admin/billings/'
    | '/_layout/_authenticated/admin/budgets/'
    | '/_layout/_authenticated/admin/contributors/'
    | '/_layout/_authenticated/admin/engagements/'
    | '/_layout/_authenticated/admin/projects/'
    | '/_layout/_authenticated/admin/reports/'
    | '/_layout/_authenticated/client/$engagementId/'
    | '/_layout/_authenticated/client/$engagementId/projects/$slug'
    | '/_layout/_authenticated/client/$engagementId/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work': {
      id: '/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof LayoutWorkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/treasury': {
      id: '/_layout/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof LayoutTreasuryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sign-in': {
      id: '/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LayoutSignInRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reset-password': {
      id: '/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LayoutResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apply': {
      id: '/_layout/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof LayoutApplyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/$slug': {
      id: '/_layout/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof LayoutDocsSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accept-invitation/$id': {
      id: '/_layout/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/welcome': {
      id: '/_layout/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof LayoutAuthenticatedWelcomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/profile': {
      id: '/_layout/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthenticatedProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/notifications': {
      id: '/_layout/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/platform': {
      id: '/_layout/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof LayoutAuthenticatedPlatformRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/client': {
      id: '/_layout/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof LayoutAuthenticatedClientRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/platform/': {
      id: '/_layout/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof LayoutAuthenticatedPlatformIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedPlatformRouteRoute
    }
    '/_layout/_authenticated/client/': {
      id: '/_layout/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof LayoutAuthenticatedClientIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/admin/': {
      id: '/_layout/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/settings': {
      id: '/_layout/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAuthenticatedAdminSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/members': {
      id: '/_layout/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof LayoutAuthenticatedAdminMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId': {
      id: '/_layout/_authenticated/client/$engagementId'
      path: '/$engagementId'
      fullPath: '/client/$engagementId'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRouteImport
      parentRoute: typeof LayoutAuthenticatedClientRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/': {
      id: '/_layout/_authenticated/client/$engagementId/'
      path: '/'
      fullPath: '/client/$engagementId/'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
    '/_layout/_authenticated/admin/reports/': {
      id: '/_layout/_authenticated/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/projects/': {
      id: '/_layout/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/engagements/': {
      id: '/_layout/_authenticated/admin/engagements/'
      path: '/engagements'
      fullPath: '/admin/engagements/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminEngagementsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/contributors/': {
      id: '/_layout/_authenticated/admin/contributors/'
      path: '/contributors'
      fullPath: '/admin/contributors/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminContributorsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/budgets/': {
      id: '/_layout/_authenticated/admin/budgets/'
      path: '/budgets'
      fullPath: '/admin/budgets/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminBudgetsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/billings/': {
      id: '/_layout/_authenticated/admin/billings/'
      path: '/billings'
      fullPath: '/admin/billings/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminBillingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/applications/': {
      id: '/_layout/_authenticated/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/reports': {
      id: '/_layout/_authenticated/client/$engagementId/reports'
      path: '/reports'
      fullPath: '/client/$engagementId/reports'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdReportsRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/prepayments': {
      id: '/_layout/_authenticated/client/$engagementId/prepayments'
      path: '/prepayments'
      fullPath: '/client/$engagementId/prepayments'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdPrepaymentsRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/billings': {
      id: '/_layout/_authenticated/client/$engagementId/billings'
      path: '/billings'
      fullPath: '/client/$engagementId/billings'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdBillingsRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
    '/_layout/_authenticated/admin/projects/$slug': {
      id: '/_layout/_authenticated/admin/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/admin/projects/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedAdminProjectsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/engagements/$engagementId': {
      id: '/_layout/_authenticated/admin/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/admin/engagements/$engagementId'
      preLoaderRoute: typeof LayoutAuthenticatedAdminEngagementsEngagementIdRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/admin/contributors/$nearAccount': {
      id: '/_layout/_authenticated/admin/contributors/$nearAccount'
      path: '/contributors/$nearAccount'
      fullPath: '/admin/contributors/$nearAccount'
      preLoaderRoute: typeof LayoutAuthenticatedAdminContributorsNearAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/projects/': {
      id: '/_layout/_authenticated/client/$engagementId/projects/'
      path: '/projects'
      fullPath: '/client/$engagementId/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
    '/_layout/_authenticated/client/$engagementId/projects/$slug': {
      id: '/_layout/_authenticated/client/$engagementId/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/client/$engagementId/projects/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedClientEngagementIdProjectsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteRouteChildren {
  LayoutAuthenticatedAdminMembersRoute: typeof LayoutAuthenticatedAdminMembersRoute
  LayoutAuthenticatedAdminSettingsRoute: typeof LayoutAuthenticatedAdminSettingsRoute
  LayoutAuthenticatedAdminIndexRoute: typeof LayoutAuthenticatedAdminIndexRoute
  LayoutAuthenticatedAdminContributorsNearAccountRoute: typeof LayoutAuthenticatedAdminContributorsNearAccountRoute
  LayoutAuthenticatedAdminEngagementsEngagementIdRoute: typeof LayoutAuthenticatedAdminEngagementsEngagementIdRoute
  LayoutAuthenticatedAdminProjectsSlugRoute: typeof LayoutAuthenticatedAdminProjectsSlugRoute
  LayoutAuthenticatedAdminApplicationsIndexRoute: typeof LayoutAuthenticatedAdminApplicationsIndexRoute
  LayoutAuthenticatedAdminBillingsIndexRoute: typeof LayoutAuthenticatedAdminBillingsIndexRoute
  LayoutAuthenticatedAdminBudgetsIndexRoute: typeof LayoutAuthenticatedAdminBudgetsIndexRoute
  LayoutAuthenticatedAdminContributorsIndexRoute: typeof LayoutAuthenticatedAdminContributorsIndexRoute
  LayoutAuthenticatedAdminEngagementsIndexRoute: typeof LayoutAuthenticatedAdminEngagementsIndexRoute
  LayoutAuthenticatedAdminProjectsIndexRoute: typeof LayoutAuthenticatedAdminProjectsIndexRoute
  LayoutAuthenticatedAdminReportsIndexRoute: typeof LayoutAuthenticatedAdminReportsIndexRoute
}

const LayoutAuthenticatedAdminRouteRouteChildren: LayoutAuthenticatedAdminRouteRouteChildren =
  {
    LayoutAuthenticatedAdminMembersRoute: LayoutAuthenticatedAdminMembersRoute,
    LayoutAuthenticatedAdminSettingsRoute:
      LayoutAuthenticatedAdminSettingsRoute,
    LayoutAuthenticatedAdminIndexRoute: LayoutAuthenticatedAdminIndexRoute,
    LayoutAuthenticatedAdminContributorsNearAccountRoute:
      LayoutAuthenticatedAdminContributorsNearAccountRoute,
    LayoutAuthenticatedAdminEngagementsEngagementIdRoute:
      LayoutAuthenticatedAdminEngagementsEngagementIdRoute,
    LayoutAuthenticatedAdminProjectsSlugRoute:
      LayoutAuthenticatedAdminProjectsSlugRoute,
    LayoutAuthenticatedAdminApplicationsIndexRoute:
      LayoutAuthenticatedAdminApplicationsIndexRoute,
    LayoutAuthenticatedAdminBillingsIndexRoute:
      LayoutAuthenticatedAdminBillingsIndexRoute,
    LayoutAuthenticatedAdminBudgetsIndexRoute:
      LayoutAuthenticatedAdminBudgetsIndexRoute,
    LayoutAuthenticatedAdminContributorsIndexRoute:
      LayoutAuthenticatedAdminContributorsIndexRoute,
    LayoutAuthenticatedAdminEngagementsIndexRoute:
      LayoutAuthenticatedAdminEngagementsIndexRoute,
    LayoutAuthenticatedAdminProjectsIndexRoute:
      LayoutAuthenticatedAdminProjectsIndexRoute,
    LayoutAuthenticatedAdminReportsIndexRoute:
      LayoutAuthenticatedAdminReportsIndexRoute,
  }

const LayoutAuthenticatedAdminRouteRouteWithChildren =
  LayoutAuthenticatedAdminRouteRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteRouteChildren,
  )

interface LayoutAuthenticatedClientEngagementIdRouteRouteChildren {
  LayoutAuthenticatedClientEngagementIdBillingsRoute: typeof LayoutAuthenticatedClientEngagementIdBillingsRoute
  LayoutAuthenticatedClientEngagementIdPrepaymentsRoute: typeof LayoutAuthenticatedClientEngagementIdPrepaymentsRoute
  LayoutAuthenticatedClientEngagementIdReportsRoute: typeof LayoutAuthenticatedClientEngagementIdReportsRoute
  LayoutAuthenticatedClientEngagementIdIndexRoute: typeof LayoutAuthenticatedClientEngagementIdIndexRoute
  LayoutAuthenticatedClientEngagementIdProjectsSlugRoute: typeof LayoutAuthenticatedClientEngagementIdProjectsSlugRoute
  LayoutAuthenticatedClientEngagementIdProjectsIndexRoute: typeof LayoutAuthenticatedClientEngagementIdProjectsIndexRoute
}

const LayoutAuthenticatedClientEngagementIdRouteRouteChildren: LayoutAuthenticatedClientEngagementIdRouteRouteChildren =
  {
    LayoutAuthenticatedClientEngagementIdBillingsRoute:
      LayoutAuthenticatedClientEngagementIdBillingsRoute,
    LayoutAuthenticatedClientEngagementIdPrepaymentsRoute:
      LayoutAuthenticatedClientEngagementIdPrepaymentsRoute,
    LayoutAuthenticatedClientEngagementIdReportsRoute:
      LayoutAuthenticatedClientEngagementIdReportsRoute,
    LayoutAuthenticatedClientEngagementIdIndexRoute:
      LayoutAuthenticatedClientEngagementIdIndexRoute,
    LayoutAuthenticatedClientEngagementIdProjectsSlugRoute:
      LayoutAuthenticatedClientEngagementIdProjectsSlugRoute,
    LayoutAuthenticatedClientEngagementIdProjectsIndexRoute:
      LayoutAuthenticatedClientEngagementIdProjectsIndexRoute,
  }

const LayoutAuthenticatedClientEngagementIdRouteRouteWithChildren =
  LayoutAuthenticatedClientEngagementIdRouteRoute._addFileChildren(
    LayoutAuthenticatedClientEngagementIdRouteRouteChildren,
  )

interface LayoutAuthenticatedClientRouteRouteChildren {
  LayoutAuthenticatedClientEngagementIdRouteRoute: typeof LayoutAuthenticatedClientEngagementIdRouteRouteWithChildren
  LayoutAuthenticatedClientIndexRoute: typeof LayoutAuthenticatedClientIndexRoute
}

const LayoutAuthenticatedClientRouteRouteChildren: LayoutAuthenticatedClientRouteRouteChildren =
  {
    LayoutAuthenticatedClientEngagementIdRouteRoute:
      LayoutAuthenticatedClientEngagementIdRouteRouteWithChildren,
    LayoutAuthenticatedClientIndexRoute: LayoutAuthenticatedClientIndexRoute,
  }

const LayoutAuthenticatedClientRouteRouteWithChildren =
  LayoutAuthenticatedClientRouteRoute._addFileChildren(
    LayoutAuthenticatedClientRouteRouteChildren,
  )

interface LayoutAuthenticatedPlatformRouteRouteChildren {
  LayoutAuthenticatedPlatformIndexRoute: typeof LayoutAuthenticatedPlatformIndexRoute
}

const LayoutAuthenticatedPlatformRouteRouteChildren: LayoutAuthenticatedPlatformRouteRouteChildren =
  {
    LayoutAuthenticatedPlatformIndexRoute:
      LayoutAuthenticatedPlatformIndexRoute,
  }

const LayoutAuthenticatedPlatformRouteRouteWithChildren =
  LayoutAuthenticatedPlatformRouteRoute._addFileChildren(
    LayoutAuthenticatedPlatformRouteRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRouteRoute: typeof LayoutAuthenticatedAdminRouteRouteWithChildren
  LayoutAuthenticatedClientRouteRoute: typeof LayoutAuthenticatedClientRouteRouteWithChildren
  LayoutAuthenticatedPlatformRouteRoute: typeof LayoutAuthenticatedPlatformRouteRouteWithChildren
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRoute
  LayoutAuthenticatedNotificationsRoute: typeof LayoutAuthenticatedNotificationsRoute
  LayoutAuthenticatedProfileRoute: typeof LayoutAuthenticatedProfileRoute
  LayoutAuthenticatedWelcomeRoute: typeof LayoutAuthenticatedWelcomeRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRouteRoute:
    LayoutAuthenticatedAdminRouteRouteWithChildren,
  LayoutAuthenticatedClientRouteRoute:
    LayoutAuthenticatedClientRouteRouteWithChildren,
  LayoutAuthenticatedPlatformRouteRoute:
    LayoutAuthenticatedPlatformRouteRouteWithChildren,
  LayoutAuthenticatedDashboardRoute: LayoutAuthenticatedDashboardRoute,
  LayoutAuthenticatedNotificationsRoute: LayoutAuthenticatedNotificationsRoute,
  LayoutAuthenticatedProfileRoute: LayoutAuthenticatedProfileRoute,
  LayoutAuthenticatedWelcomeRoute: LayoutAuthenticatedWelcomeRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutApplyRoute: typeof LayoutApplyRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutRegisterRoute: typeof LayoutRegisterRoute
  LayoutResetPasswordRoute: typeof LayoutResetPasswordRoute
  LayoutSignInRoute: typeof LayoutSignInRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutTreasuryRoute: typeof LayoutTreasuryRoute
  LayoutWorkRoute: typeof LayoutWorkRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAcceptInvitationIdRoute: typeof LayoutAcceptInvitationIdRoute
  LayoutDocsSlugRoute: typeof LayoutDocsSlugRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutApplyRoute: LayoutApplyRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutRegisterRoute: LayoutRegisterRoute,
  LayoutResetPasswordRoute: LayoutResetPasswordRoute,
  LayoutSignInRoute: LayoutSignInRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutTreasuryRoute: LayoutTreasuryRoute,
  LayoutWorkRoute: LayoutWorkRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAcceptInvitationIdRoute: LayoutAcceptInvitationIdRoute,
  LayoutDocsSlugRoute: LayoutDocsSlugRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
