/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkRouteImport } from './routes/_layout/work'
import { Route as LayoutTreasuryRouteImport } from './routes/_layout/treasury'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutRegisterRouteImport } from './routes/_layout/register'
import { Route as LayoutPayoutsRouteImport } from './routes/_layout/payouts'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutApplyRouteImport } from './routes/_layout/apply'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutDocsIndexRouteImport } from './routes/_layout/docs/index'
import { Route as LayoutDocsSlugRouteImport } from './routes/_layout/docs/$slug'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedProfileRouteImport } from './routes/_layout/_authenticated/profile'
import { Route as LayoutAuthenticatedConfiguredRouteImport } from './routes/_layout/_authenticated/_configured'
import { Route as LayoutAuthenticatedConfiguredAdminRouteImport } from './routes/_layout/_authenticated/_configured/_admin'
import { Route as LayoutAuthenticatedConfiguredAdminAdminRouteImport } from './routes/_layout/_authenticated/_configured/_admin/admin'
import { Route as LayoutAuthenticatedConfiguredAdminAdminIndexRouteImport } from './routes/_layout/_authenticated/_configured/_admin/admin.index'
import { Route as LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRouteImport } from './routes/_layout/_authenticated/_configured/_admin/admin.projects.index'
import { Route as LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRouteImport } from './routes/_layout/_authenticated/_configured/_admin/admin/projects.$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkRoute = LayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTreasuryRoute = LayoutTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegisterRoute = LayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayoutsRoute = LayoutPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplyRoute = LayoutApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsSlugRoute = LayoutDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProfileRoute =
  LayoutAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedConfiguredRoute =
  LayoutAuthenticatedConfiguredRouteImport.update({
    id: '/_configured',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedConfiguredAdminRoute =
  LayoutAuthenticatedConfiguredAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LayoutAuthenticatedConfiguredRoute,
  } as any)
const LayoutAuthenticatedConfiguredAdminAdminRoute =
  LayoutAuthenticatedConfiguredAdminAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedConfiguredAdminRoute,
  } as any)
const LayoutAuthenticatedConfiguredAdminAdminIndexRoute =
  LayoutAuthenticatedConfiguredAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedConfiguredAdminAdminRoute,
  } as any)
const LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute =
  LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedConfiguredAdminAdminRoute,
  } as any)
const LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute =
  LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => LayoutAuthenticatedConfiguredAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/payouts': typeof LayoutPayoutsRoute
  '/register': typeof LayoutRegisterRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/admin': typeof LayoutAuthenticatedConfiguredAdminAdminRouteWithChildren
  '/admin/': typeof LayoutAuthenticatedConfiguredAdminAdminIndexRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute
  '/admin/projects/': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/apply': typeof LayoutApplyRoute
  '/contact': typeof LayoutContactRoute
  '/payouts': typeof LayoutPayoutsRoute
  '/register': typeof LayoutRegisterRoute
  '/team': typeof LayoutTeamRoute
  '/treasury': typeof LayoutTreasuryRoute
  '/work': typeof LayoutWorkRoute
  '/profile': typeof LayoutAuthenticatedProfileRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/docs/$slug': typeof LayoutDocsSlugRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/admin': typeof LayoutAuthenticatedConfiguredAdminAdminIndexRoute
  '/admin/projects/$slug': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute
  '/admin/projects': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/apply': typeof LayoutApplyRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/payouts': typeof LayoutPayoutsRoute
  '/_layout/register': typeof LayoutRegisterRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/treasury': typeof LayoutTreasuryRoute
  '/_layout/work': typeof LayoutWorkRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/_configured': typeof LayoutAuthenticatedConfiguredRouteWithChildren
  '/_layout/_authenticated/profile': typeof LayoutAuthenticatedProfileRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRoute
  '/_layout/docs/$slug': typeof LayoutDocsSlugRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/_authenticated/_configured/_admin': typeof LayoutAuthenticatedConfiguredAdminRouteWithChildren
  '/_layout/_authenticated/_configured/_admin/admin': typeof LayoutAuthenticatedConfiguredAdminAdminRouteWithChildren
  '/_layout/_authenticated/_configured/_admin/admin/': typeof LayoutAuthenticatedConfiguredAdminAdminIndexRoute
  '/_layout/_authenticated/_configured/_admin/admin/projects/$slug': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute
  '/_layout/_authenticated/_configured/_admin/admin/projects/': typeof LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/payouts'
    | '/register'
    | '/team'
    | '/treasury'
    | '/work'
    | '/profile'
    | '/settings'
    | '/docs/$slug'
    | '/docs/'
    | '/admin'
    | '/admin/'
    | '/admin/projects/$slug'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/payouts'
    | '/register'
    | '/team'
    | '/treasury'
    | '/work'
    | '/profile'
    | '/settings'
    | '/docs/$slug'
    | '/docs'
    | '/admin'
    | '/admin/projects/$slug'
    | '/admin/projects'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/apply'
    | '/_layout/contact'
    | '/_layout/payouts'
    | '/_layout/register'
    | '/_layout/team'
    | '/_layout/treasury'
    | '/_layout/work'
    | '/_layout/'
    | '/_layout/_authenticated/_configured'
    | '/_layout/_authenticated/profile'
    | '/_layout/_authenticated/settings'
    | '/_layout/docs/$slug'
    | '/_layout/docs/'
    | '/_layout/_authenticated/_configured/_admin'
    | '/_layout/_authenticated/_configured/_admin/admin'
    | '/_layout/_authenticated/_configured/_admin/admin/'
    | '/_layout/_authenticated/_configured/_admin/admin/projects/$slug'
    | '/_layout/_authenticated/_configured/_admin/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work': {
      id: '/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof LayoutWorkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/treasury': {
      id: '/_layout/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof LayoutTreasuryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payouts': {
      id: '/_layout/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof LayoutPayoutsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apply': {
      id: '/_layout/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof LayoutApplyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/$slug': {
      id: '/_layout/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof LayoutDocsSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/profile': {
      id: '/_layout/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthenticatedProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_configured': {
      id: '/_layout/_authenticated/_configured'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_configured/_admin': {
      id: '/_layout/_authenticated/_configured/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedConfiguredRoute
    }
    '/_layout/_authenticated/_configured/_admin/admin': {
      id: '/_layout/_authenticated/_configured/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredAdminAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedConfiguredAdminRoute
    }
    '/_layout/_authenticated/_configured/_admin/admin/': {
      id: '/_layout/_authenticated/_configured/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredAdminAdminIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedConfiguredAdminAdminRoute
    }
    '/_layout/_authenticated/_configured/_admin/admin/projects/': {
      id: '/_layout/_authenticated/_configured/_admin/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedConfiguredAdminAdminRoute
    }
    '/_layout/_authenticated/_configured/_admin/admin/projects/$slug': {
      id: '/_layout/_authenticated/_configured/_admin/admin/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/admin/projects/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedConfiguredAdminAdminRoute
    }
  }
}

interface LayoutAuthenticatedConfiguredAdminAdminRouteChildren {
  LayoutAuthenticatedConfiguredAdminAdminIndexRoute: typeof LayoutAuthenticatedConfiguredAdminAdminIndexRoute
  LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute: typeof LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute
  LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute: typeof LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute
}

const LayoutAuthenticatedConfiguredAdminAdminRouteChildren: LayoutAuthenticatedConfiguredAdminAdminRouteChildren =
  {
    LayoutAuthenticatedConfiguredAdminAdminIndexRoute:
      LayoutAuthenticatedConfiguredAdminAdminIndexRoute,
    LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute:
      LayoutAuthenticatedConfiguredAdminAdminProjectsSlugRoute,
    LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute:
      LayoutAuthenticatedConfiguredAdminAdminProjectsIndexRoute,
  }

const LayoutAuthenticatedConfiguredAdminAdminRouteWithChildren =
  LayoutAuthenticatedConfiguredAdminAdminRoute._addFileChildren(
    LayoutAuthenticatedConfiguredAdminAdminRouteChildren,
  )

interface LayoutAuthenticatedConfiguredAdminRouteChildren {
  LayoutAuthenticatedConfiguredAdminAdminRoute: typeof LayoutAuthenticatedConfiguredAdminAdminRouteWithChildren
}

const LayoutAuthenticatedConfiguredAdminRouteChildren: LayoutAuthenticatedConfiguredAdminRouteChildren =
  {
    LayoutAuthenticatedConfiguredAdminAdminRoute:
      LayoutAuthenticatedConfiguredAdminAdminRouteWithChildren,
  }

const LayoutAuthenticatedConfiguredAdminRouteWithChildren =
  LayoutAuthenticatedConfiguredAdminRoute._addFileChildren(
    LayoutAuthenticatedConfiguredAdminRouteChildren,
  )

interface LayoutAuthenticatedConfiguredRouteChildren {
  LayoutAuthenticatedConfiguredAdminRoute: typeof LayoutAuthenticatedConfiguredAdminRouteWithChildren
}

const LayoutAuthenticatedConfiguredRouteChildren: LayoutAuthenticatedConfiguredRouteChildren =
  {
    LayoutAuthenticatedConfiguredAdminRoute:
      LayoutAuthenticatedConfiguredAdminRouteWithChildren,
  }

const LayoutAuthenticatedConfiguredRouteWithChildren =
  LayoutAuthenticatedConfiguredRoute._addFileChildren(
    LayoutAuthenticatedConfiguredRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedConfiguredRoute: typeof LayoutAuthenticatedConfiguredRouteWithChildren
  LayoutAuthenticatedProfileRoute: typeof LayoutAuthenticatedProfileRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedConfiguredRoute:
    LayoutAuthenticatedConfiguredRouteWithChildren,
  LayoutAuthenticatedProfileRoute: LayoutAuthenticatedProfileRoute,
  LayoutAuthenticatedSettingsRoute: LayoutAuthenticatedSettingsRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutApplyRoute: typeof LayoutApplyRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutPayoutsRoute: typeof LayoutPayoutsRoute
  LayoutRegisterRoute: typeof LayoutRegisterRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutTreasuryRoute: typeof LayoutTreasuryRoute
  LayoutWorkRoute: typeof LayoutWorkRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDocsSlugRoute: typeof LayoutDocsSlugRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutApplyRoute: LayoutApplyRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutPayoutsRoute: LayoutPayoutsRoute,
  LayoutRegisterRoute: LayoutRegisterRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutTreasuryRoute: LayoutTreasuryRoute,
  LayoutWorkRoute: LayoutWorkRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDocsSlugRoute: LayoutDocsSlugRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
